[package]
name = "okane-golden"
authors = ["kikeg"]
version = "0.2.0"
edition = "2018"
rust-version = "1.31.0"
license = "Apache-2.0"
repository = "https://github.com/xkikeg/okane-golden"

[dependencies]
